name: Refresh Bundles

on:
  workflow_dispatch:
  schedule:
    # Run every 30 minutes
    - cron: '*/60 * * * *'
  push:
    branches:
      - main

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Call refresh endpoint
        env:
          SECRET: ${{ secrets.AUTHENTICATION_SECRET }}
        run: |
          TIMESTAMP=$(date +%s)
          PAYLOAD="refresh:$TIMESTAMP"
          HMAC=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$SECRET" | sed 's/^.* //')
          curl -X POST "https://revanced-external-bundles.onrender.com/refresh/bundlesMetadata" \
                -H "Authorization: Bearer $TIMESTAMP-$HMAC" \
                -H 'accept: application/json' \
                -d '' \
                -w "\nHTTP Status: %{http_code}\n"
